version: '3.7'

services:
  mls_service:
    build: ./mls-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./mls-service/:/app/
    ports:
      - 8001:8000
    environment:
      - DATABASE_URI=postgresql://postgres:0ixdEvKUMAe7Ie8sRoXg@example-db-mls.cluster-ctr2cyii89uy.us-west-2.rds.amazonaws.com:5432/postgres
      - PROPERTY_SERVICE_HOST_URL=http://property_service:8000/api/v1/properties/
    depends_on:
      - mls_db

  mls_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_mls:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=test-user
      - POSTGRES_PASSWORD=PassyTh3W0rd!
      - POSTGRES_DB=postgres

  property_service:
    build: ./property-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./property-service/:/app/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URI=postgresql://postgres:0ixdEvKUMAe7Ie8sRoXg@example-db-properties.cluster-ctr2cyii89uy.us-west-2.rds.amazonaws.com:5432/postgres
    depends_on:
      - property_db

  property_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_property:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=test-user
      - POSTGRES_PASSWORD=PassyTh3W0rd!
      - POSTGRES_DB=postgres

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - property_service
      - mls_service

volumes:
  postgres_data_mls:
  postgres_data_property: